### PR TITLE
Add `nullableItems` to ArraySchema and DictionarySchema

### PR DESCRIPTION
**Pull request by daviwil**
This is needed to enable https://github.com/Azure/autorest.modelerfour/pull/298 for issue https://github.com/Azure/autorest.modelerfour/issues/269.

### CODE REVIEW

**Comment by fearthecowboy** [comment]
O_O.

_(buckle up kids, this is where OpenAPI takes us into muddy waters)_

Before going down this path -- this creates an awful crazy problem, and I don't have the answer.

The trouble is, `nullable` should be a usage constraint, not a declaration attribute. 

This *WILL* show up with enums, because people can create virtually identical inline enums (and probably happens with objects), where that one is `x-nullable`, the other isn't. 

Then you have two types that are, and should be the same. 

I'm dancing around this same problem with ADL too -- while `nullable` can be attached to the type, it's often not the actual intent to have a type that is `{...}  | null`  but rather that a given property that uses that type can be null. 

Ping me when you're online and we can talk about it more.

**Comment by daviwil** [comment]
@fearthecowboy I've dropped `nullable` again on schema types and added `nullableItems` on ArraySchema and DictionarySchema.  What do you think?

**Review by MiYanni — APPROVED** [review]
Makes sense to me. Arrays/dictionaries are usage of types just like parameters and properties.

**Comment by daviwil** [comment]
Confirmed with @fearthecowboy over IM that `nullableItems` is a suitable name, merging this so that I can pull it into https://github.com/Azure/autorest.modelerfour/issues/269.

**Pull request merged**
