### PR TITLE
Update languages.ts

### PR DESCRIPTION
**Pull request by dolauli**
CsharpLanguage is a class without any members. Changing it to the class Language makes more sense here.

### CODE REVIEW

**Comment by fearthecowboy** [comment]
@pakrym  We never ended up doing anything special with `CSharpLanguage`  -- the schema currently uses that. Would you be impacted if we just changed the type to Language (which is functionally identical (a dictionary anyway) , but I don't know if you have any code that is specific to the naming in that)

**Comment by pakrym** [comment]
It would be a tiny breaking change that's very easy to react to. I'm OK with it, thank you for ccing me.

**Comment by daviwil** [comment]
@dolauli Could you rebase on `master` and then run the following to regenerate the schemas:

```
cd codemodel
npm install
node .scripts/generate-schema.js
```

Once you've done that, commit the `json` and `yaml` files that were updated and push them to this PR.  Once we have that we can merge it.

Thanks!

**Comment by dolauli** [comment]
> @dolauli Could you rebase on `master` and then run the following to regenerate the schemas:
> 
> ```
> cd codemodel
> npm install
> node .scripts/generate-schema.js
> ```
> 
> Once you've done that, commit the `json` and `yaml` files that were updated and push them to this PR. Once we have that we can merge it.
> 
> Thanks!

@daviwil Please help review it.

**Review by daviwil — APPROVED** [review]

**Comment by daviwil** [comment]
Thanks @dolauli!

**Pull request merged**
